[build]
builder = "nixpacks"

# BACKEND SERVICE
[service.sparkops_staging_backend]
root = "backend"
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"

# FRONTEND SERVICE
[service.sparkops_staging_frontend]
root = "frontend"
builder = "nixpacks"
