[build]
builder = "nixpacks"

# BACKEND SERVICE
[service.sparkops_staging_backend]
root = "backend"
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
watchPatterns = ["backend/**"]

# FRONTEND SERVICE
[service.sparkops_staging_frontend]
root = "frontend"
builder = "nixpacks"
watchPatterns = ["frontend/**"]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
sleepApplication = false
