#!/bin/bash

# Railway Environment Variables Setup Script
# This script outputs the environment variables needed for Railway deployment

echo "=== Railway Environment Variables Setup ==="
echo ""
echo "Copy these variables to your Railway project settings:"
echo ""
echo "🔧 REQUIRED VARIABLES:"
echo ""
echo "# Database Connection"
echo "DATABASE_URL=postgresql://username:password@host:port/database"
echo ""
echo "# Authentication"
echo "SUPABASE_JWT_SECRET=your-supabase-jwt-secret"
echo "NEXT_PUBLIC_SUPABASE_URL=https://your-project.supabase.co"
echo "SUPABASE_URL=https://your-project.supabase.co"
echo ""
echo "# Service Configuration"
echo "SECRET_KEY=your-secret-key-here"
echo "OPENAI_API_KEY=your-openai-api-key"
echo "FRONTEND_URL=https://your-frontend-domain.railway.app"
echo ""
echo "🔧 OPTIONAL VARIABLES (for integrations):"
echo ""
echo "# Xero Integration"
echo "XERO_CLIENT_ID=your-xero-client-id"
echo "XERO_CLIENT_SECRET=your-xero-client-secret"
echo "XERO_REDIRECT_URI=https://your-backend-domain.railway.app/api/integrations/xero/callback"
echo "XERO_SCOPES=openid profile email offline_access accounting.transactions accounting.contacts"
echo "XERO_STATE_SECRET=your-xero-state-secret"
echo ""
echo "# Stripe Integration"
echo "STRIPE_BASE_PRICE_ID=price_your_base_price_id"
echo "STRIPE_SEAT_PRICE_ID=price_your_seat_price_id"
echo ""
echo "🔧 RAILWAY-SPECIFIC VARIABLES (automatically set):"
echo "RAILWAY_ENVIRONMENT=staging"
echo "RAILWAY_SERVICE_NAME=sparkops_staging_backend"
echo "PORT=8000"
echo ""
echo "=== Setup Instructions ==="
echo "1. Go to your Railway project"
echo "2. Click on your backend service"
echo "3. Go to 'Variables' tab"
echo "4. Add all the required variables above"
echo "5. Redeploy the service"
echo ""
echo "=== Testing ==="
echo "After deployment, test:"
echo "curl https://your-backend-domain.railway.app/health"
echo ""
echo "Should return:"
echo '{"status":"healthy","service":"tradeops-data-factory","version":"1.0.0"}'
